
@startuml


skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 60

' List client service components/participants here

actor enduser

box "router"
participant scope
participant browser_pipeline
end box

box "plugs"
participant set_user
end box

box "auth_controller" #Lightgreen
participant request_function
participant callback_function
participant signin_function
participant insert_or_update_user_function
end box

box "check_controller" #LightBlue
participant index_function
end box


box "github"
participant github_com
end box

box "browser"
participant cookies
end box

box postgres
database discuss_dev_users_table
end box

group Request_flow

enduser -> index_function
index_function -> index_function : render index.html

@enduml
